# Generated by Django 5.2.8 on 2025-12-02 13:49

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Latitude (e.g. 54.608)', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Longitude (e.g. 18.800)', max_digits=9, null=True)),
                ('location_details', models.CharField(blank=True, help_text="Specific details (e.g. 'Entrance no. 14, park near the hotel')", max_length=255)),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro Only')], default='beginner', max_length=20)),
                ('surf_break_type', models.CharField(choices=[('beach_break', 'Beach Break'), ('reef_break', 'Reef Break'), ('point_break', 'Point Break'), ('rivermouth', 'Rivermouth'), ('jetty_pier', 'Jetty / Pier')], default='beach_break', max_length=20)),
                ('wave_direction', models.CharField(choices=[('right', 'Right'), ('left', 'Left'), ('a_frame', 'A-Frame')], default='a_frame', max_length=20)),
                ('optimal_swell_direction', models.CharField(blank=True, help_text='e.g. NW, N (Direction from which the swell works best)', max_length=100)),
                ('optimal_wind_direction', models.CharField(blank=True, help_text='e.g. SE (Offshore wind direction)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='General description of the vibe and spot')),
                ('image', models.ImageField(blank=True, null=True, upload_to='spots_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
