# Generated by Django 5.2.8 on 2026-07-24 16:11

import core.validators
import django.core.validators
import surfingproject.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0003_spotphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=surfingproject.uploads.spot_image_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_uploaded_image]),
        ),
        migrations.AlterField(
            model_name='spotphoto',
            name='image',
            field=models.ImageField(upload_to=surfingproject.uploads.spot_gallery_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_uploaded_image]),
        ),
    ]
