# Generated by Django 5.2.8 on 2025-12-02 15:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spots', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date of the session.')),
                ('start_time', models.TimeField(help_text='Start time of the session.')),
                ('end_time', models.TimeField(blank=True, help_text='Optional end time of the session.', null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, help_text='Maximum number of participants (optional).', null=True)),
                ('note', models.TextField(blank=True, help_text='Additional information (meeting point, required level, etc.).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When this session was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='When this session was last updated.')),
                ('organizer', models.ForeignKey(help_text='User who created this session.', on_delete=django.db.models.deletion.CASCADE, related_name='organized_sessions', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, help_text='Users who joined this session.', related_name='joined_sessions', to=settings.AUTH_USER_MODEL)),
                ('spot', models.ForeignKey(help_text='Surf spot where this session will take place.', on_delete=django.db.models.deletion.CASCADE, related_name='surf_sessions', to='spots.spot')),
            ],
            options={
                'verbose_name': 'Session',
                'verbose_name_plural': 'Sessions',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
