# Generated by Django 5.2.8 on 2025-12-02 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0001_initial'),
        ('surf_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['date', 'start_time']},
        ),
        migrations.AddField(
            model_name='session',
            name='name',
            field=models.CharField(default='Default session', help_text='A descriptive name for the session.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='session',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='organizer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organized_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='joined_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='spots.spot'),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
