# Generated by Django 5.2.8 on 2026-04-20 12:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spots', '0002_alter_spot_latitude_alter_spot_longitude'),
        ('surf_sessions', '0002_alter_session_options_session_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['date', 'start_time'], name='surf_sessio_date_4a0bcf_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['organizer', 'date'], name='surf_sessio_organiz_d8a40c_idx'),
        ),
    ]
