# Generated by Django 5.2.8 on 2026-05-06 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="following",
            field=models.ManyToManyField(blank=True, related_name="followers", symmetrical=False, to="accounts.customuser"),
        ),
    ]
