# Generated by Django 5.2.8 on 2026-07-24 16:11

import core.validators
import django.core.validators
import surfingproject.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_customuser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pictures/default_profile.jpg', upload_to=surfingproject.uploads.profile_picture_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_uploaded_image]),
        ),
    ]
